# Generated by Django 4.2.2 on 2023-09-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnyStudent',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_username', models.CharField(max_length=50)),
                ('student_password', models.CharField(max_length=60)),
                ('student_contact', models.BigIntegerField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CreateProject',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('student_name', models.CharField(max_length=100)),
                ('student_roll', models.CharField(max_length=10)),
                ('project_file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('Institute_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Institute_username', models.CharField(max_length=50)),
                ('Institute_password', models.CharField(max_length=20)),
                ('Institute_address', models.CharField(max_length=200)),
                ('Institute_email', models.EmailField(max_length=254)),
                ('Institute_contact', models.BigIntegerField()),
                ('Institute_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInstituteStudent',
            fields=[
                ('Istudent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Istudent_username', models.CharField(max_length=20)),
                ('Istudent_contact', models.BigIntegerField()),
                ('Istudent_email', models.EmailField(max_length=254)),
                ('Istudent_year_in_institute', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2)),
                ('Istudent_major', models.CharField(max_length=20)),
                ('Istudent_instituteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprouthub.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('project_files', models.FileField(upload_to='')),
                ('project_studentId', models.ManyToManyField(to='sprouthub.projectinstitutestudent')),
            ],
        ),
    ]
