# Generated by Django 4.2.2 on 2023-09-22 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprouthub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproject',
            name='student_email',
            field=models.EmailField(default=datetime.datetime(2023, 9, 22, 13, 7, 23, 359653, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
