# Generated by Django 4.2.2 on 2023-09-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprouthub', '0002_createproject_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproject',
            name='student_email',
            field=models.EmailField(max_length=254),
        ),
    ]
