# Generated by Django 4.2.2 on 2023-09-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprouthub', '0003_alter_createproject_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('student_name', models.CharField(max_length=100)),
                ('student_roll', models.CharField(max_length=10)),
                ('project_file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CreateProject',
        ),
    ]
