# Generated by Django 4.2.2 on 2023-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprouthub', '0004_project_delete_createproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='student_email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
    ]
